# Generated by Django 4.1.7 on 2023-03-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_ordercharger_battery_voltage_ordercharger_car_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercharger',
            name='car_title',
            field=models.CharField(default='Не указано', max_length=50, verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='ordercharger',
            name='slot_number',
            field=models.IntegerField(null=True, verbose_name='Номер стоянки'),
        ),
        migrations.AlterField(
            model_name='ordercharger',
            name='status',
            field=models.IntegerField(default=4, verbose_name='Статус стоянки'),
        ),
    ]
