# Generated by Django 4.1.7 on 2023-03-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_alter_ordercharger_car_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercharger',
            name='charge_percent',
            field=models.FloatField(null=True, verbose_name='Текущий процент зарядки'),
        ),
        migrations.AlterField(
            model_name='ordercharger',
            name='battery_voltage',
            field=models.CharField(max_length=50, null=True, verbose_name='Напряжение батареи'),
        ),
        migrations.AlterField(
            model_name='ordercharger',
            name='car_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='ordercharger',
            name='slot_number',
            field=models.IntegerField(null=True, verbose_name='Номер парковки'),
        ),
        migrations.AlterField(
            model_name='ordercharger',
            name='start_charge_time',
            field=models.CharField(max_length=50, null=True, verbose_name='Время заправки'),
        ),
        migrations.AlterField(
            model_name='ordercharger',
            name='status',
            field=models.IntegerField(null=True, verbose_name='Статус парковочного места'),
        ),
    ]
