# Generated by Django 4.1.7 on 2023-03-10 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_ordercharger_charge_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercharger',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordercharger',
            name='end_charge_time',
            field=models.CharField(max_length=50, null=True, verbose_name='Время окончания заправки'),
        ),
    ]
